version: "3.9"

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.17.0.0/16
          gateway: 10.17.0.1

services:
  autoheal:
      image: willfarrell/autoheal:latest
      tty: true
      restart: always
      environment:
        - AUTOHEAL_INTERVAL=60
        - AUTOHEAL_START_PERIOD=300
        - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  dns:
    build: 
      context: ./bind9
    container_name: bind
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - ./bind9:/etc/bind
    networks:
      network:
        ipv4_address: 10.17.0.3

  proxy:
    build: 
      context: .
    container_name: proxy
    command: sh /app/connect.sh
    restart: always
    volumes:
      - ./key.pem:/app/key.pem
    ports:
      - '1089:1089'
      - '1089:1089/udp'
    networks:
      network:
        ipv4_address: 10.17.0.2
    healthcheck:
      test: curl --fail -x socks5h://0.0.0.0:1089 ifconfig.io || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    env_file:
      - .env