version: "3.9"

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.17.0.0/16
          gateway: 10.17.0.1

services:
  autoheal:
      container_name: healer
      image: willfarrell/autoheal:latest
      tty: true
      restart: always
      environment:
        - AUTOHEAL_INTERVAL=60
        - AUTOHEAL_START_PERIOD=300
        - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  proxy:
    image: erfanshekari/ssh-proxy:latest
    container_name: proxy
    command: sh /manage/start.sh
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always
    volumes:
      - ./bind9:/etc/bind
      - ${SSH_KEY}:/app/key.pem
    networks:
      network:
        ipv4_address: 10.17.0.2
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    healthcheck:
      test: curl --fail ifconfig.io || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    env_file:
      - .env

  v2fly:
    image: v2fly/v2fly-core:latest
    container_name: v2fly
    command: run -c /etc/v2fly/config.json
    restart: always
    network_mode: "service:proxy"
    volumes:
      - ./v2ray.config.json:/etc/v2fly/config.json