version: "3.9"

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.17.0.0/16
          gateway: 10.17.0.1

services:
  autoheal:
      container_name: healer
      image: willfarrell/autoheal:latest
      tty: true
      restart: always
      environment:
        - AUTOHEAL_INTERVAL=60
        - AUTOHEAL_START_PERIOD=300
        - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  proxy:
    build:
      context: ./socks
    container_name: proxy
    restart: always
    command: sh /app/start.ssh.sh
    expose:
      - 1089
    networks:
      network:
        ipv4_address: 10.17.0.2
    depends_on:
      - dns
    volumes:
      - ${SSH_KEY}:/app/key.pem
    healthcheck:
      test: curl --fail -x socks5h://localhost:1089 ifconfig.io || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    env_file:
      - .env
    

  dns:
    build: 
      context: .
    container_name: dns
    command: sh /manage/start.sshuttle.sh
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always
    volumes:
      - ./bind9:/etc/bind
      - ${SSH_KEY}:/app/key.pem
    networks:
      network:
        ipv4_address: 10.17.0.3
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    env_file:
      - .env
    healthcheck:
      test: host google.com 0.0.0.0 || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
