version: "3.9"

services:
  autoheal:
      image: willfarrell/autoheal:latest
      tty: true
      restart: always
      environment:
        - AUTOHEAL_INTERVAL=60
        - AUTOHEAL_START_PERIOD=300
        - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  ssh-proxy:
    image: erfanshekari/ssh-proxy:latest
    container_name: ssh-proxy
    command: sh /app/connect.sh
    restart: always
    volumes:
      - ./key.pem:/app/key.pem
    ports:
      - '1089:1089'
      - '1089:1089/udp'
    healthcheck:
      test: curl --fail -x socks5h://0.0.0.0:1089 ifconfig.io || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    environment:
      - SSH_HOST=18.141.172.144
      - SSH_PORT=22
      - SSH_USER=ubuntu
      - SSH_KEY=/app/key.pem
      - SOCKS5_PORT=1089